services:          #default synxtax
  database1:        #naming convention for container
    build: /opt/Employee-3tire/psql-database/ #location of the docker file
    ports:     #port mapping my container to host port 
      - '5432:5432'  
    container_name: contfirstd  #providing name to container
    network_mode:   #providing network mode
        bridge
  backend1:        #naming convention for container
    build: /opt/Employee-3tire/backend/ #location of the docker file
    ports:     #port mapping my container to host port 
      - '8080:8080'  
    container_name: contfirstb  #providing name to container
    network_mode:   #providing network mode
        bridge
  frontend11:        #naming convention for container
    build: /opt/Employee-3tire/frontend/ #location of the docker file
    ports:     #port mapping my container to host port 
      - '3000:3000'  
    container_name: contfirstf  #providing name to container
    network_mode:   #providing network mode
        bridge